<?xml version="1.0"?>
<package format="2">
  <name>rosout_print</name>
  <version>0.0.0</version>
  <description>Tool converting rosout_agg messages to log message forms</description>

  <maintainer email="cposteam@clearpath.ai">Clearpath OS Team</maintainer>
  <author email="cposteam@clearpath.ai">Clearpath OS Team</author>

  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rosbag</depend>
  <depend>rosbag_manager_msgs</depend>
  <depend>roscpp</depend>
  <depend>rosgraph_msgs</depend>

  <test_depend>catkin_clang_format</test_depend>
  <test_depend>clang-format-18</test_depend>
</package>
